# Generated by Django 3.1.5 on 2021-02-06 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('username', models.CharField(help_text='Username', max_length=30, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Phone number', max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phoneNum', message='Enter a valid Phone Number', regex='[0-9]{10}')])),
                ('dataNascimento', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=30)),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
