# Generated by Django 3.1.5 on 2021-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('MÉDICO', 'Médico'), ('SECRETÁRIA', 'Secretária')], default='SECRETÁRIA', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, help_text='Username', max_length=30, unique=True),
        ),
    ]
