# Generated by Django 3.1.5 on 2021-02-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('anotacaoConsulta', models.TextField()),
                ('dataRetorno', models.DateField()),
                ('anotacaoRetorno', models.TextField()),
            ],
            options={
                'verbose_name': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=25)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('cidade', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='ConsultaExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(max_length=250)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_exa', to='patient.consulta')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_exa', to='patient.exame')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='exames',
            field=models.ManyToManyField(related_name='consulta', through='patient.ConsultaExame', to='patient.Exame'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='patient.paciente'),
        ),
    ]
