# Generated by Django 3.1.5 on 2021-01-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='andress',
            new_name='adress',
        ),
    ]
