# Generated by Django 3.1.5 on 2021-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='anotacaoConsulta',
            field=models.TextField(verbose_name='Anotação da Consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dataRetorno',
            field=models.DateField(verbose_name='Data de Retorno'),
        ),
    ]
